class RRF:
    def __init__(self):
        self.query = {
            "retriever": {
                "rrf": {
                    "retrievers": [],
                }
            }
        }

    def add_retrievers(self, retrievers):
        for retriver in retrievers:
            self.query["retriever"]["rrf"]["retrievers"].append(retriver.get_query())
        return self

    def get_query(self):
        return self.query


class RRF_Retriever:
    def __init__(self):
        self.query = {"standard": {"query": {}}}

    def get_query(self):
        return self.query


class RRF_Keyword_Retriever(RRF_Retriever):
    def __init__(self, item_name="keyword", keywords=""):
        super().__init__()
        query = {"terms": {item_name: keywords}}
        self.query["standard"]["query"] = query


class RRF_Match_Retriever(RRF_Retriever):
    def __init__(self, item_name="content", content=""):
        super().__init__()
        query = {"match": {item_name: {"query": content}}}
        self.query["standard"]["query"] = query


class RRF_Exists_Retriever(RRF_Retriever):
    """
    Retriever for checking whether a field exists, used to boost documents with a specific attribute
    """

    def __init__(self, field: str, boost: float = 1.0):
        super().__init__()
        self.query["standard"]["query"] = {"exists": {"field": field, "boost": boost}}


class RRF_Semantic_Retriever(RRF_Retriever):
    def __init__(self, item_name="semantic", content=""):
        super().__init__()
        query = {
            item_name: {
                "field": "semantic",
                "query": content,
            }
        }
        self.query["standard"]["query"] = query


class RRF_Vector_Retriever(RRF_Retriever):
    """
    Vector retriever wrapper for dense_vector fields
    """

    def __init__(self, vector_field="semantic", query_vector=None):
        super().__init__()
        # Remove the empty standard query generated by the parent class to avoid ES parse errors
        if "standard" in self.query:
            del self.query["standard"]

        # For dense_vector fields, regular 'match' or 'semantic' queries can no longer be used
        # Use 'knn' syntax for querying [2]
        knn_query = {
            "field": vector_field,
            "query_vector": query_vector,  # This must be the 4096-dimensional float array generated by your model
            "k": 10,  # Final number of nearest-neighbor documents returned
            "num_candidates": 100,  # Number of candidates retrieved per shard, recommended around 10 times k
        }

        # In the RRF (Reciprocal Rank Fusion) architecture,
        # vector queries are usually combined with standard queries as an independent branch [1]
        # Note: this assumes the parent structure supports direct assignment to knn
        self.query["knn"] = knn_query
